require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SinkCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # SinkCategory. As you add validations to SinkCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all sink_categories as @sink_categories" do
      sink_category = SinkCategory.create! valid_attributes
      get :index
      assigns(:sink_categories).should eq([sink_category])
    end
  end

  describe "GET show" do
    it "assigns the requested sink_category as @sink_category" do
      sink_category = SinkCategory.create! valid_attributes
      get :show, :id => sink_category.id.to_s
      assigns(:sink_category).should eq(sink_category)
    end
  end

  describe "GET new" do
    it "assigns a new sink_category as @sink_category" do
      get :new
      assigns(:sink_category).should be_a_new(SinkCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested sink_category as @sink_category" do
      sink_category = SinkCategory.create! valid_attributes
      get :edit, :id => sink_category.id.to_s
      assigns(:sink_category).should eq(sink_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SinkCategory" do
        expect {
          post :create, :sink_category => valid_attributes
        }.to change(SinkCategory, :count).by(1)
      end

      it "assigns a newly created sink_category as @sink_category" do
        post :create, :sink_category => valid_attributes
        assigns(:sink_category).should be_a(SinkCategory)
        assigns(:sink_category).should be_persisted
      end

      it "redirects to the created sink_category" do
        post :create, :sink_category => valid_attributes
        response.should redirect_to(SinkCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sink_category as @sink_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        SinkCategory.any_instance.stub(:save).and_return(false)
        post :create, :sink_category => {}
        assigns(:sink_category).should be_a_new(SinkCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SinkCategory.any_instance.stub(:save).and_return(false)
        post :create, :sink_category => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sink_category" do
        sink_category = SinkCategory.create! valid_attributes
        # Assuming there are no other sink_categories in the database, this
        # specifies that the SinkCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SinkCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => sink_category.id, :sink_category => {'these' => 'params'}
      end

      it "assigns the requested sink_category as @sink_category" do
        sink_category = SinkCategory.create! valid_attributes
        put :update, :id => sink_category.id, :sink_category => valid_attributes
        assigns(:sink_category).should eq(sink_category)
      end

      it "redirects to the sink_category" do
        sink_category = SinkCategory.create! valid_attributes
        put :update, :id => sink_category.id, :sink_category => valid_attributes
        response.should redirect_to(sink_category)
      end
    end

    describe "with invalid params" do
      it "assigns the sink_category as @sink_category" do
        sink_category = SinkCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SinkCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => sink_category.id.to_s, :sink_category => {}
        assigns(:sink_category).should eq(sink_category)
      end

      it "re-renders the 'edit' template" do
        sink_category = SinkCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SinkCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => sink_category.id.to_s, :sink_category => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sink_category" do
      sink_category = SinkCategory.create! valid_attributes
      expect {
        delete :destroy, :id => sink_category.id.to_s
      }.to change(SinkCategory, :count).by(-1)
    end

    it "redirects to the sink_categories list" do
      sink_category = SinkCategory.create! valid_attributes
      delete :destroy, :id => sink_category.id.to_s
      response.should redirect_to(sink_categories_url)
    end
  end

end
